lite client cmds
cosmos/relayer-archive pull request #9
Opened 2020-01-24 15:29 UTC by cmwaters

in response to #7 and #1

Made some of the changes that Jack suggested including using `getChain` instead of using a liteClient map, converted cmds into function in `relayer/verifier.go`, removed most function level variables

2020-01-24 18:57 UTC, jackzampolin commented on cmd/lite.go
> +	updatePeriod time.Duration
This is nicer as a flag than passed in via config 👍 ✨

2020-01-24 19:15 UTC, jackzampolin commented on cmd/lite.go
> +		updatePeriod, _ = cmd.Flags().GetDuration("update-period")
Would be nice to have that `update-period` string in a package level var.

2020-01-24 19:16 UTC, jackzampolin commented on cmd/lite.go
> +		return chain.StartLiteClient(filepath.Join(liteDir, chainID), updatePeriod)
Does this call block? Is there any logging here?

2020-01-24 19:21 UTC, jackzampolin commented on cmd/lite.go
> +	Use: "header [chain-id] [height]",
Would be nice to have a command to fetch roots of trust (headers) and valsets from an endpoint too.

2020-01-24 19:23 UTC, jackzampolin commented on relayer/verifier.go
> +func (c *Chain) StartLiteClient(dbDir string, updatePeriod time.Duration) error {
How to run this in a goroutine?

2020-01-27 08:41 UTC, melekes commented
https://github.com/cosmos/relayer/pull/3#pullrequestreview-347506317 review should be taken into account

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +		return chain.StartLiteClient(filepath.Join(liteDir, chainID), updatePeriod)
`start` (needs to be renamed to `reset`) cmd should call an HTTP endpoint I believe https://github.com/cosmos/relayer/issues/5#issuecomment-578656671

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +		chain, err := relayer.GetChain(chainID, config.c)
same here, but for now, we can leave these to empty

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +var liteGetHeaderCmd = &cobra.Command{
```suggestion
var liteHeaderCmd = &cobra.Command{
```

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +		if len(args) == 1 {
```go
switch len(args) {
  case 1:
  case 2:
  default:
    return errors.New("expected either 1 or 2 arguments")
}
```

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +		if len(args) == 1 { // return latest validator set
```go
switch len(args) {
  case 1:
  case 2:
  default:
    return errors.New("expected either 1 or 2 arguments")
}
```

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +var liteGetValidatorsCmd = &cobra.Command{
```suggestion
var liteValidatorsCmd = &cobra.Command{
```

https://golang.org/doc/effective_go.html#Getters

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +			header, err := chain.LiteClient.TrustedHeader(0, time.Now())
You need to use the DB directly. Initializing a new client just to query something is not an option. You can initialize the DB store here https://godoc.org/github.com/tendermint/tendermint/lite2/store/db and use it to query headers / validator sets

2020-01-27 11:33 UTC, melekes commented on cmd/lite.go
> +		lc := chain.LiteClient
You need to use the DB directly. Initializing a new client just to query something is not an option. You can initialize the DB store here https://godoc.org/github.com/tendermint/tendermint/lite2/store/db and use it to query headers / validator sets

2020-01-27 14:59 UTC, cmwaters commented on cmd/lite.go
> +		updatePeriod, _ = cmd.Flags().GetDuration("update-period")
update-period is now part of the config file

2020-01-27 15:03 UTC, cmwaters commented on cmd/lite.go
> +		if len(args) == 1 {
What's the rationale behind using this?

2020-01-27 17:23 UTC, melekes commented on cmd/lite.go
> +		if len(args) == 1 {
switch has a better structure

2020-01-27 18:25 UTC, jackzampolin commented on cmd/config.go
> +		updatePeriod, err := time.ParseDuration(i.UpdatePeriod)
Maybe we do this check as we read in the config and set it on the `Chain` abstraction?

2020-01-27 18:27 UTC, jackzampolin commented on cmd/lite.go
> +			header, err := chain.LiteClient.TrustedHeader(0, time.Now())
Seems like this functionality should be in the `Chain` abstraction

2020-01-27 18:27 UTC, jackzampolin commented on cmd/start.go
> +		// initiate a lite client for each chain declared in the config file
Nice!

2020-01-27 18:28 UTC, jackzampolin commented on relayer/chain.go
> +	logger       log.Logger
Are we setting/using this logger anywhere? Seems like this could be used to give chain specific error messages.

2020-01-27 19:40 UTC, cmwaters commented on relayer/chain.go
> +	logger       log.Logger
Yeah I started with some of the chain abstraction:
```
func (c *Chain) LatestHeight() uint64 {
	height, err := c.LiteClient.LastTrustedHeight()
	if err != nil {
		c.logger.Error("lite client does not have a last trusted height", err)
		height = 0
	}
	return uint64(height)
}
```

2020-01-27 20:03 UTC, jackzampolin commented on relayer/chain.go
> +	logger       log.Logger
Nice! I will integrate this more deeply. Doesn't need to be in scope for this PR.

2020-01-29 19:03 UTC, fedekunze requested changes
👍

2020-01-29 19:03 UTC, fedekunze commented on cmd/config.go
> +			return nil
```suggestion
			return err
```

2020-01-29 19:03 UTC, fedekunze commented on cmd/config.go
>  			return nil
```suggestion
			return err
```

2020-01-29 19:03 UTC, fedekunze commented on relayer/verifier.go
> +		return fmt.Errorf("instance of lite client already running for this chain")
```suggestion
		return errors.New("instance of lite client already running for this chain")
```

2020-01-29 19:03 UTC, fedekunze commented on relayer/verifier.go
> +	return err
```suggestion
	if err != nil {
	    return err
	}
	return nil
```

2020-02-01 01:43 UTC, jackzampolin commented
Pushed some changes here. Going to go ahead and merge it. Let's continue the work on another branch. While working with the code one thing I noticed was that there is some confusion over what the various lite client commands should be doing. Lets grab some time next week to clear that up.

2020-02-01 01:43 UTC, merged